// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOP2i29nbGUV4ni4bQp-f0Biyysb0q6UM',
    appId: '1:309379094838:web:e7fcae7d1b9eb982e0fb97',
    messagingSenderId: '309379094838',
    projectId: 'chatwave-84602',
    authDomain: 'chatwave-84602.firebaseapp.com',
    storageBucket: 'chatwave-84602.appspot.com',
    measurementId: 'G-F12K17K14V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRkD5z3Hq2dqoyDZGoX0bfFz50H71rC88',
    appId: '1:309379094838:android:76a0e45bcd461ed5e0fb97',
    messagingSenderId: '309379094838',
    projectId: 'chatwave-84602',
    storageBucket: 'chatwave-84602.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA671dPXyIVzPns0PHAeu8dZsFrKKcCRbA',
    appId: '1:309379094838:ios:a396fa0b991f5a93e0fb97',
    messagingSenderId: '309379094838',
    projectId: 'chatwave-84602',
    storageBucket: 'chatwave-84602.appspot.com',
    androidClientId: '309379094838-qb8qlh2m7rfe34t75c06i7lggrrasp68.apps.googleusercontent.com',
    iosClientId: '309379094838-jsv3qaps2gpviggee123on71asgrcih0.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatwave',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA671dPXyIVzPns0PHAeu8dZsFrKKcCRbA',
    appId: '1:309379094838:ios:9589146f16f3be31e0fb97',
    messagingSenderId: '309379094838',
    projectId: 'chatwave-84602',
    storageBucket: 'chatwave-84602.appspot.com',
    androidClientId: '309379094838-qb8qlh2m7rfe34t75c06i7lggrrasp68.apps.googleusercontent.com',
    iosClientId: '309379094838-lg66136e5h0b683lkpet1bfbns2oeifj.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatwave.RunnerTests',
  );
}
